name: Lint Awesome List
on: workflow_dispatch
jobs:
  lint:
    name: Lint
    runs-on: codebuild-gitrunner_clay-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - name: Checkout code
      run: |
        echo "Hello"
